project:
  type: book

book:
  title: "metodos_quantitativos"
  author: "Norah Jones"
  date: "15/02/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - aula01.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

